### PR TITLE
spree 3.1 stable changes

### PR DESCRIPTION
**Pull request by emrox**
* switched to spree_core 3.1.0 stable
* use `mail.deliver_now` instead of deprecated `mail.deliver`
* rspec 3 refactorings & fixes

### CODE REVIEW

**Comment by emrox** [comment]
and let's discuss these houndci-bot warnings ;)

**Comment by emrox** [comment]
also failing tests due to "Unable to find Mozilla geckodriver" and/or failing bundler. Maybe someone can help here?

**Comment by davidhuff2014** [comment]
That may have been fixed in travis-ci, if not limit the version of selenium-webdriver < 3 in the gemspec.

**Comment by emrox** [comment]
I'm no longer interested in this PR since I currently not working with Spree Commerce anymore. So I'll close it. Feel free to reopen it if you are interested

**Pull request closed without merging**
